/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Fri Oct  7 17:01:08 2016. */

#include "measurement.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Measurement_fields[4] = {
    PB_FIELD(100, FLOAT   , OPTIONAL, STATIC  , FIRST, Measurement, temperature, temperature, 0),
    PB_FIELD(101, FLOAT   , OPTIONAL, STATIC  , OTHER, Measurement, humidity, temperature, 0),
    PB_FIELD(110, UINT32  , REPEATED, CALLBACK, OTHER, Measurement, analog_readings, humidity, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
